### ISSUE TITLE
The report cannot show the detail of all vulnerabilities.

### ISSUE THREAD

**Issue by uonghoangminhchau** [APTRS/APTRS#14]
# Make sure you have gone through the Documentation
https://anof-cyber.github.io/APTRS/#/

**Describe the bug**
I have exported a web pentest report, which including 7 vulnerabilities in total. But in the PDF file only showed the detail of 6 vulnerabilities. Whichever vulnerability I added more, they wont be showed in the PDF report file. 
Seem like the report cannot show more than 6 vulnerabilities in detail. I tried to create another project to test and it was the same

**Expected behavior**
The report should show all the vulnerabilities.

**Comment by Anof-cyber** [comment]
Can you confirm if all the vulnerabilities are in the same project. Also can you try restarting the application.

**Comment by uonghoangminhchau** [comment]
Yes, its the same project. I tried restarting many times. I don't know if it was only me or anyone else meeting this issue.

**Comment by uonghoangminhchau** [comment]
yes, full detail of others, but none for the 7th vul. The limit is only 6.
