### ISSUE TITLE
Vulnerability Title can't be selected

### ISSUE THREAD

**Issue by 50YUD4N60** [APTRS/APTRS#15]
# Make sure you have gone through the Documentation
https://anof-cyber.github.io/APTRS/#/

**Describe the bug**
Can't "Tab", mouse hover the Title list to selected the stored vulnerabilities from database on the "Add vulnerability" page under Projects

**To Reproduce**
1. Go to "Project"
2. Click on 'View'
4. Click on 'Vulnerability'
5. Click on 'Add New'
6. Type "SQL" in the Vulnerability Title bar, use either cursor or tab or enter
7. Failed to select the store vulnerabilities

**Expected behavior**
Expect to load the vulnerability database by cursor-click, tab or enter but not type each word exact fit to the stored vulnerability title in the vulnerability database.

**Screenshots**
![image](https://user-images.githubusercontent.com/125332597/218636786-7516d865-c3c2-48c9-bd35-95a3ffa0964b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS 22.04 jammy
 - Browser: Firefox
 - Python Version: Python 3.10.6
 - Pip Version: pip 22.0.2
 - wkhtmltopdf Version: 0.12.6.1 (with patched qt)
 
**Additional context**

**Comment by Anof-cyber** [comment]
The issues have been identified and will be fixed in the upcoming release.
