### ISSUE TITLE
Not able to add logo in add company

### ISSUE THREAD

**Issue by EdigaPrudhviGoud** [APTRS/APTRS#25]
# Make sure you have gone through the Documentation
https://anof-cyber.github.io/APTRS/#/

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python Version [e.g. 3.10]
 - Pip Version[e.g. 20]
 - wkhtmltopdf Version [e.g. 0.12.6-3]
 
**Additional context**

**Comment by Anof-cyber** [comment]
Done
