### ISSUE TITLE
Changing the color of PFD report

### ISSUE THREAD

**Issue by MustaqeemIAli** [APTRS/APTRS#29]
![image](https://github.com/APTRS/APTRS/assets/109740034/722c315b-1b39-4939-97e7-fdb4ca78cc59)
Description:
I am encountering an issue when generating PDFs from HTML content, the page size remains fixed, leading to blank white space when the HTML content does not fill the entire page.

Expected Behavior:
I expect the PDF page to be a defined color and not white.

Steps to Reproduce:

Generate a PDF from HTML content where the content height varies with a darker background.
Observe the PDF output to see that the pdf page is white from where the html content ends.

**Comment by Anof-cyber** [comment]
This issue has been resolved and an update is currently in development.
