### ISSUE TITLE
install.bat version check

### ISSUE THREAD

**Issue by FatherGuidoSarducci** [APTRS/APTRS#6]
When using Python 3.10 and 3.11, the install.bat script terminates during version check because "Python 3.10" and "Python 3.11" are considered less than "Python 3.8"

```
FOR /F "tokens=* USEBACKQ" %%F IN (`python --version`) DO (
SET var=%%F
)
ECHO %var%
if "%var%" GEQ "Python 3.8" (
    echo Python 3.8 and above found
  ) else (
    echo "%var%"
    echo APTRS require Python 3.8+ .
    exit /b
  )
```

**Comment by Anof-cyber** [comment]
This is an known issue. The windows batch script doesn't support version comparison. A updated script will be released in new few days.

As of now you can modify the below line
`if "%var%" GEQ "Python 3.8"` to `if "%var%" GEQ "Python 3.[8.9.10]"`

**Comment by m-raheem** [comment]
`setlocal enabledelayedexpansion

:: Get Python version
FOR /F "tokens=2 delims= " %%F IN ('python --version 2^>^&1') DO (
    SET version=%%F
)

:: Extract major, minor, and patch versions
FOR /F "tokens=1,2,3 delims=." %%A IN ("%version%") DO (
    SET major=%%A
    SET minor=%%B
    SET patch=%%C
)

:: Compare versions
IF %major% GEQ 3 (
    IF %minor% GEQ 8 (
        echo Python 3.8 and above found
        
    )
) else (

echo %version%
echo APTRS require Python 3.8+.
exit /b 1
)

`

**Comment by m-raheem** [comment]
Add it after @echo off 
replacing the check part
its working for me
